version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RACK_ENV: development
      RAILS_ENV: development
      SECRET_KEY_BASE: 
      RAILS_MAX_THREADS: 4
      WEB_CONCURRENCY: 4
      DB_POOL: 12
    depends_on:
      - db
    expose:
      - "3000"
    restart: unless-stopped
    privileged: true
    networks:
      - web
      - default
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.hitchi.frontend.rule=Host:www.hitchi.de"
      - "traefik.hitchi.port=3000"
      - "traefik.hitchi.protocol=http"

  db:
    image: postgres:11.2-alpine
    environment:
      TZ: 'Europe/Berlin'
    restart: always

networks:
  web:
    external: true
