version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RACK_ENV: production
      RAILS_ENV: production
      RAILS_MAX_THREADS: 4
      WEB_CONCURRENCY: 4
      DB_POOL: 12
    depends_on:
      - box_of_gems
      - db
    volumes:
      - box_of_gems:/box_of_gems
    restart: unless-stopped
    privileged: true
    networks:
      - web
      - default
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.hitchi.frontend.rule=Host:www.hitchi.de"
      - "traefik.hitchi.port=3000"
      - "traefik.hitchi.protocol=http"

  db:
    image: postgres:11.2-alpine
    environment:
      TZ: 'Europe/Berlin'
    restart: always

  box_of_gems:
    image: busybox
    restart: unless-stopped
    volumes:
      - box_of_gems:/box_of_gems

volumes:
  box_of_gems:

networks:
  web:
    external: true
